name: yty_claim_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  dynamic_color: ^1.7.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
